### ISSUE TITLE
Admin page Stored Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by fvi-att** [enhavo/enhavo#459]
## Summary

[enhavo CMS](https://www.enhavo.com/) has XSS security issue on the admin page.
An authorized attacker can put any kind of javascript. And it is executed on authorized victim browser without induce

## Reproduction

Here is how to reproduce this issue.

 1. Access to the admin page. 
 1. Create an Usergroup as payloads.
 1. Back to admin user group page.

Then you find that dialog appeared and XSS  happens.

## Payloads

Set Usergroup as following.

```html
<img src=x onerror="alert(document.cookie);"/>
```

## Event

- 2018-03-05 Vuln is discovered.
- 2018-03-06 Contact to developers.
- 2018-03-13 Open an issue.

**Comment by fvi-att** [comment]
CVE-2018-8832 is assigned

**Comment by gseidel** [comment]
The was fixed with the new UI upgrade #611

**Comment by NicoleG25** [comment]
@gseidel , could you please point out what was the vulnerable file?
Thanks in advance :)

**Comment by gseidel** [comment]
@NicoleG25 The problem was the file ``src/Enhavo/Bundle/AppBundle/Table/TableWidgetRenderer.php`` and parent file ``src/Enhavo/Bundle/AppBundle/Type/AbstractRenderer.php``

The configuration set the return value as html safe (The rendering engine twig would escape dynamic values be default), which is not true for rendering the table grid, because it contains unsafe user values.
```
return array(
    new \Twig_SimpleFunction($this->getName(), array($this, 'render'), array('is_safe' => array('html'))),
);
```

The ``TableWidgetRenderer`` was removed by mentioned PR, because the rendering is forwarded to ``vue.js``, which escape html chars by default as well, but no configuration is changing the ``vue.js`` behaviour.

**Comment by NicoleG25** [comment]
> @NicoleG25 The problem was the file `src/Enhavo/Bundle/AppBundle/Table/TableWidgetRenderer.php` and parent file `src/Enhavo/Bundle/AppBundle/Type/AbstractRenderer.php`
> 
> The configuration set the return value as html safe (The rendering engine twig would escape dynamic values be default), which is not true for rendering the table grid, because it contains unsafe user values.
> 
> ```
> return array(
>     new \Twig_SimpleFunction($this->getName(), array($this, 'render'), array('is_safe' => array('html'))),
> );
> ```
> 
> The `TableWidgetRenderer` was removed by mentioned PR, because the rendering is forwarded to `vue.js`, which escape html chars by default as well, but no configuration is changing the `vue.js` behaviour.

Thank you !
